---
version: "3"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # (Optional) Enable Dashboard, don't do in production
      - 8080:8080
    volumes:
      - ${TRAEFIK_CONFIGDIR}:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro

    restart: unless-stopped
    networks:
      traefik_net:
        # Fix traefik to a specific IP from the traefik_net
        # Used to resolve trusted proxy issues with some apps (e.g. Home Assistant)
        ipv4_address: ${TRAEFIK_INTERNAL_IP}
    dns:
      # Local DNS server serving the internal domain names
      - ${LOCAL_DNS_SERVER}

networks:
  traefik_net:
    external: true
